version: "3.7"
services:
  app-1:
    build: ./app-1
    ports: 
    - target: 5000
      published: 5000
      protocol: tcp


  app-2:
    build: ./app-2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp

